### ISSUE TITLE
Add new parameter to also delete attached assets (files) on each release prior to release deleting

### ISSUE THREAD

**Issue by thadguidry** [dev-drprasad/delete-older-releases#1]
So this seems to work as advertised...but not quite what we expected! :-)

See my note on our issue in OpenRefine: https://github.com/OpenRefine/OpenRefine/issues/2462#issuecomment-645529774

So I think a new parameter is needed perhaps?  "delete_assets_for_release"?
1. That would gather the release asset_id's https://developer.github.com/v3/repos/releases/#list-release-assets
2. and then Delete the release assets with https://developer.github.com/v3/repos/releases/#delete-a-release-asset
3. Finally, deleting the X number of releases themselves.

**Comment by dev-drprasad** [comment]
If you're taking about list of releases listed in
https://github.com/OpenRefine/OpenRefine-nightly-releases/releases?after=3.4-beta-109-g4e9d365, I don't think these releases still exist cuz assets that are not deleted. These releases (I 
 think they are called "archive files") exist for every tag, the repo has. 

The only way to remove these archive files is to delete corresponding tags. Let me know If I understood something wrong

**Comment by thadguidry** [comment]
@dev-drprasad 

From https://help.github.com/en/github/administering-a-repository/about-releases
>Releases are based on Git tags, which mark a specific point in your repository's history. A tag date may be different than a release date since they can be created at different times. For more information about viewing your existing tags, see "[Viewing your repository's releases and tags.](https://help.github.com/en/github/administering-a-repository/viewing-your-repositorys-releases-and-tags)"

So after deleting the release...
We probably need to offer an additional parameter that will delete the tag and assets?

https://developer.github.com/v3/repos/releases/#delete-a-release-asset

Unfortunately, since Releases in GitHub are in fact based on tags as shown in the quote above, when you create a release, it's required to give it a tag.  Which we do.

So we just need to delete the tags additionally.
Unfortunately still, [GitHub does not currently supply an API endpoint to delete tags](https://developer.github.com/v3/git/tags/) and so regular Git commands need to be used instead via a shell script, etc.  Read more:
https://www.abeautifulsite.net/how-to-delete-a-tag-on-github

**Comment by dev-drprasad** [comment]
@thadguidry 

GitHub API supports deleting of tags https://developer.github.com/v3/git/refs/#example-deleting-a-tag
I can add new config property `delete_tags` (type: boolean) to specify, whether to delete tags or not

**Comment by thadguidry** [comment]
@dev-drprasad Great!  Ready to test when you have it available!

**Comment by thadguidry** [comment]
Also Reddy, you should signup for **https://github.com/sponsors**, so some folks can pay you :-) 
But for now, send me a private email to my email address thadguidry@gmail.com so that I can at least compensate you some for your time in helping us here!

**Comment by dev-drprasad** [comment]
@thadguidry 

I released this under [v0.1.0](https://github.com/dev-drprasad/delete-older-releases/releases/tag/v0.1.0). You don't need to update in your workflow.

> I can at least compensate you some for your time in helping us here!

Thanks for offering. But don't mind it. It is open source project and other people going to use it. Although, I am available for part-time work, adhoc work on hourly based. If you need to get any task done, drop me mail at dev.drprasad@aim.com.

I made this https://gist.github.com/dev-drprasad/6162929c3d7ed900dcbd2cf6f804a980 to help you cleanup your old tags. I see lot of them :) . You need to run this multiple times with prefixes like `3.4-beta`, `3.3-beta`. ☠️ CAUTION: I haven't tested it properly ☠️
