### ISSUE TITLE
It is not deleting older releases, simply the last releases in the list.

### ISSUE THREAD

**Issue by okibcn** [dev-drprasad/delete-older-releases#14]
When several jobs in the same repo are generating different releases with different names — For instance, when releasing the same code for different platforms.

In such case, the releases are not sorted by date. The action should order the releases by date, and then keep the most recent ones.

**Comment by thadguidry** [comment]
Where or what area are you seeing the "not sorted by date" specifically?  Some GitHub view or an API query?

**Comment by okibcn** [comment]
When I use `gh release list`, all the releases are sorted by date. but not when I go to the releases or tag page online. Or when I do a json query like:
`curl -v "https://api.github.com/repos/OWNER/REPO/tags"`

I don't know this action is sorting the releases and tags to select the oldest, but for sure it is not deleting the oldest releases and unused tags. It is just keeping the first on the list.

**Comment by okibcn** [comment]
I am now using this action in my daily build of OpenWrt firmware for 3 routers here: https://github.com/okibcn/myopenwrt/releases

As you can see, the repo lists the releases not in chronological order, and this action is deleting the last in line that, sometimes are the most recent releases. This is why I am actually confming that thedelete-older-releases is not actually deleting the older releases, but the last of a list that is not chronological.

**Comment by smallprogram** [comment]
+1

**Comment by okibcn** [comment]
I had to abandon this action. I built my own one using a short shell script using the gh API.

**Comment by smallprogram** [comment]
@okibcn @thadguidry Fixed

**Comment by thadguidry** [comment]
@smallprogram Thanks, I've reached out to @dev-drprasad on Twitter to ask for maintainer access to this repo to continue to help the community and maintain and enhance it.  Hopefully he responds soon.
