### ISSUE TITLE
Delete releases whose number of downloads is less than a specific value

### ISSUE THREAD

**Issue by steve02081504** [dev-drprasad/delete-older-releases#18]
Since shields.io's badge for download statistics only counts the last 100 releases, I wanted to keep the high downloads from the last 100 releases and remove the particularly low downloads to make the badge look better
So I was wondering if there could be a parameter that would indicate the deletion of releases with downloads below this value or a function that removes the lowest downloaded releases until the number of releases reaches a certain value?

**Comment by thadguidry** [comment]
Hmm, I think that's do-able.
Would this work for you:  a new parameter `releases_downloaded_threshold` where you set a value of `100` and a new function would delete all releases that have less than 100 downloads?

**Comment by steve02081504** [comment]
> Hmm, I think that's do-able.
> Would this work for you:  a new parameter `releases_downloaded_threshold` where you set a value of `100` and a new function would delete all releases that have less than 100 downloads?  The function would inspect the statistic in the Releases API results `GET /repos/{owner}/{repo}/releases/{release_id}` where for example `assets: [{"download_count": 42 ... }]` could be found and used.

I think this draft is great, thanks!

**Comment by thadguidry** [comment]
@smallprogram Do you think you could add this capability for us?  Seems like a fun one to work on a PR.

**Comment by smallprogram** [comment]
Maybe I can try to write it, but it will take some time, I am mainly engaged in back-end development, I am not proficient in javascript and nodejs.
