### ISSUE TITLE
Delete tags not associated with latest releases

### ISSUE THREAD

**Issue by ghost** [dev-drprasad/delete-older-releases#28]
The option to keep only the tags related to the latest releases will be very useful, I hope you'll ipmlement it in the nearest time possible.

**Comment by thadguidry** [comment]
Take a look at the other repo https://github.com/dev-drprasad/delete-tag-and-release

which alternately might work the way you need or could be used in a subsequent action call for a cleanup pass (depending on options and your specific needs).  Test tag and release deletion on a throwaway repo to ensure your needs are met well.

**Comment by smallprogram** [comment]
I don't understand this requirement, can you explain it? Or give an example
@thadguidry

**Comment by thadguidry** [comment]
I think this is a feature capability in the other Action in repo https://github.com/dev-drprasad/delete-tag-and-release

**Comment by thadguidry** [comment]
This:
> keep the tags related to the releases only and delete all the others automatically without specifying everytime.

Seems to indicate that they want handling for general git tag deletion, for example, deleting all tags NOT associated to any release.  The user could use other Actions I think on the marketplace.  But we could also add that feature to this repo as an enhancement.

**Comment by thadguidry** [comment]
BTW, I've seen other DevOps processing that calls them `orphan tags`.  But I am not sure what GitHub docs calls them.  We should use same terminology that GitHub docs uses.

**Comment by thadguidry** [comment]
Hey @ReenigneArcher do you think you might be able to implement this new option here called `delete_orphan_tags` which is default `false`?

**Comment by ReenigneArcher** [comment]
@thadguidry It's definitely possible, but if it were up to me I'd choose to keep this action as simple as possible since there is no unit/integration testing occurring.

Also, the original requester of this feature has since deleted their github account... so maybe just close this as "not planned"?
