### ISSUE TITLE
Can not delete tags

### ISSUE THREAD

**Issue by eallion** [dev-drprasad/delete-older-releases#3]
![批注 2020-09-04 205251](https://user-images.githubusercontent.com/1698841/92241445-d0bf9680-eef0-11ea-87ad-c3578d475e6e.png)

When i set `delete_tags: true`, i get this error. And the tags are not deleted.

**Comment by thadguidry** [comment]
He forgot to update the documentation README.  Take a look at the [pull request](https://github.com/dev-drprasad/delete-older-releases/pull/4/files) that I just made to get that updated.
That `delete_tags` option is no longer available, and instead it is an Environment variable: `INPUT_DELETE_TAGS`

**Comment by dev-drprasad** [comment]
> He forgot to update the documentation README. Take a look at the pull request that I just made to get that updated.
That delete_tags option is no longer available, and instead it is an Environment variable: INPUT_DELETE_TAGS

Actually I forgot to update `action.yml`. README.md is update to date.

@eallion Sorry! There was a bug and I fixed it. Please run your actions again and let me know if it still not working

**Comment by eallion** [comment]
Ok thanks

**Comment by eallion** [comment]
I rerun an action, but it may take more than 4 hrs. its here <https://github.com/eallion/openwrt/actions/runs/239686779>

**Comment by eallion** [comment]
Still get an error:

![2020-09-05_13-16](https://user-images.githubusercontent.com/1698841/92298317-3ad04e00-ef7a-11ea-84a3-a213dbffa61f.png)

**Comment by eallion** [comment]
My workflow:

![2020-09-05_13-18](https://user-images.githubusercontent.com/1698841/92298331-563b5900-ef7a-11ea-9819-30f1e3644120.png)

**Comment by thadguidry** [comment]
@eallion Change that `INPUT_DELETE_TAGS` to `delete_tags` since he fixed it now and properly added the command that was missing here: https://github.com/dev-drprasad/delete-older-releases/commit/b1e01bf0c5d758778088864df211686ac382a7e0

**Comment by eallion** [comment]
> @eallion Change that `INPUT_DELETE_TAGS` to `delete_tags` since he fixed it now and properly added the command that was missing here: [b1e01bf](https://github.com/dev-drprasad/delete-older-releases/commit/b1e01bf0c5d758778088864df211686ac382a7e0)

work fine thank you
