### ISSUE TITLE
match is broken after switch to Regex

### ISSUE THREAD

**Issue by xlighting2017** [dev-drprasad/delete-older-releases#34]
the recent commit(1c5fa812b705aa0b444b840a8528d67a6c0d9849) has changed the match from string match to regex, however, the match is broken:

the code:
```
return !item.draft && item.tag_name.match(deletePattern) !== -1 && item.assets.length > 0;
```

say, we have a `item.tag_name` = "abc", `deletePattern` = "123"

tag_name.match(deletePattern) will return `null`, and  

item.tag_name.match(deletePattern) !== -1  will be `true`

which means:  even if `delete_tag_pattern`  does NOT match, it will delete the release!

----

below is the log indicating the above logic:

releases matching **360T7** will be targeted
🌶  given `keep_min_download_counts` is 0, this will not enable the download count removal rule
🌶  given `delete_expired_data` is  0
💬  found total of 3 active release(s)
🍻  found 1 older release(s)
starting to delete **v23.9.28-ipq807x** with id 122852717

**Comment by smallprogram** [comment]
please try
