### ISSUE TITLE
error with enterprise URL 

### ISSUE THREAD

**Issue by panchalbhavesh** [dev-drprasad/delete-older-releases#37]
error: failed to get list of releases <- getaddrinfo ENOTFOUND

github_rest_api_url: {github-enterprise-url}/api/v3 not working as expected
tried with https in url as well

**Comment by thadguidry** [comment]
You should be using the URL given to you by your IT staff.  GitHub Enterprise is self hosted and so would have a different domain，for example, it might be `excelsoftware.com` and so you would use that.  Or it might be `git.excelsoftware.com` or `excelsoftware.com/github/api`.

So check with your enterprise organization.
