### ISSUE TITLE
Release not deleted if no assets attached

### ISSUE THREAD

**Issue by GeluConstantin** [dev-drprasad/delete-older-releases#39]
Hi,

the action don't delete releases which don't have assets 'attached'. I'm missing a configuration or the action is deleting releases with assets.

Thank you for the feedback!

**Comment by thadguidry** [comment]
It's likely the delete tag pattern did not match or that you have a tag with no associated releases, which in that case the `delete_tag` parameter can force a delete for them.

Take a look at the logs which will detail if matches were found to delete or not with your provided parameters.  The logs often give clues as to what is happening or why tags are not matching.
