### ISSUE TITLE
Node.js 16 deprecated

### ISSUE THREAD

**Issue by GeluConstantin** [dev-drprasad/delete-older-releases#40]
Hi,

I used the latest version of the action, v0.3.2, and got the message bellow.

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dev-drprasad/delete-older-releases@v0.3.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

When will be action with the version 20 updated? 

Thank you for the feedback!

**Comment by Ponnia-M** [comment]
i'm having this issue too.

**Comment by thadguidry** [comment]
This is now fixed in latest release [v0.3.3](https://github.com/dev-drprasad/delete-older-releases/releases/tag/v0.3.3)
