### ISSUE TITLE
Failed to get list of releases <- Not Found

### ISSUE THREAD

**Issue by ZaberZiv** [dev-drprasad/delete-older-releases#42]
Hi! Keep getting error, seems like your script can't find my releases.

Here what I add to my file:
- name: Delete
  uses: dev-drprasad/delete-older-releases@v0.3.3
     with:
         keep_latest: 0
         delete_tags: true
         delete_tag_pattern: Pre-Release
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

Here what I get:
Run dev-drprasad/delete-older-releases@v0.3.3
💬  no `repo` name given. fall-ing back to this repo
🌶  given `keep_latest` is 0, this will wipe out all releases
🔖  corresponding tags also will be deleted
releases matching Pre-Release will be targeted
🌶  given `keep_min_download_counts` is 0, this will not enable the download count removal rule
🌶  given `delete_expired_data` is  0
🌶  failed to get list of releases <- Not Found
exiting...

**Comment by thadguidry** [comment]
Are you sure you have some releases that have the string `Pre-Release` somewhere in their tags?
Example:
Release Title = myAwesomeApp-v3.2
Release Git Tag = v3.2_Pre-Release

**Comment by thadguidry** [comment]
Also, if you are looking to delete categorical "Pre-releases", then you would use our parameter `delete_prerelease_only`.

```
name: Delete
uses: dev-drprasad/delete-older-releases@v0.3.3
with:
  keep_latest: 0
  delete_tags: true
  delete_tag_pattern: v3.2
  delete_prerelease_only: true
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
```

**Comment by ZaberZiv** [comment]
> Are you sure you have some releases that have the string `Pre-Release` somewhere in their tags? Example: Release Title = myAwesomeApp-v3.2 Release Git Tag = v3.2_Pre-Release

Yes, there are two pre-leases that has string in title and tag.
![image](https://github.com/dev-drprasad/delete-older-releases/assets/53208571/d7841497-91b5-4a4b-823b-4bf2369b312a)

**Comment by ZaberZiv** [comment]
> Also, if you are looking to delete categorical "Pre-releases" https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
> 
> > Optionally, to notify users that the release is not ready for production and may be unstable, select **This is a pre-release**.
> 
> , then you would use our parameter `delete_prerelease_only`.
> 
> ```
> name: Delete
> uses: dev-drprasad/delete-older-releases@v0.3.3
> with:
>   keep_latest: 0
>   delete_tags: true
>   delete_tag_pattern: v3\.2
>   delete_prerelease_only: true
> env:
>   GITHUB_TOKEN: ${{ secrets.TOKEN }}
> ```
> 
> NOTE REMINDER: `delete_tag_pattern` takes a Regex pattern. https://github.com/dev-drprasad/delete-older-releases?tab=readme-ov-file#delete_tag_pattern

Just tried this, doesn't helped.

**Comment by thadguidry** [comment]
That string in your RELEASE TITLE is "Pre-Release v2.19.14"
What is the RELEASE TAG ?

**Comment by thadguidry** [comment]
Made using GitHub's GUI (but you might be using the GitHub CLI to make releases? which is fine also)

![image](https://github.com/dev-drprasad/delete-older-releases/assets/986438/dd443ea1-68fe-48cf-a76b-ddd09216ef0d)
![image](https://github.com/dev-drprasad/delete-older-releases/assets/986438/b51426e9-6e81-4ce6-95e7-e17ca3deb4a2)

**Comment by thadguidry** [comment]
![image](https://github.com/dev-drprasad/delete-older-releases/assets/986438/9a00ae19-bfd9-43f7-8cd8-bce9503a7c5a)

**Comment by ZaberZiv** [comment]
![image](https://github.com/dev-drprasad/delete-older-releases/assets/53208571/521672bb-1a42-409c-b255-c8d7e8371083)

**Comment by thadguidry** [comment]
so your Git Tag for that commit 1ba1189 is actually `v.2.19.14-beta` where it seems you have a `.` between the `v` and the `2`.
If you have many pre-releases and multiple tags, perhaps you want to omit using the actions `delete_tag_pattern` which will not filter on any tags and hence will remove all tags, the only other filtering mechanism is the actions parameter `delete_prerelease_only`.

So if you did this:

```
name: Delete
uses: dev-drprasad/delete-older-releases@v0.3.3
with:
  keep_latest: 0
  delete_tags: true
  delete_prerelease_only: true
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
```

Then that will essentially delete all prereleases, no matter what the labels of any of the releases' tags are.  If any of your releases are categorized as a `pre-release` then it will get deleted.  Maybe that's what you really want?

**Comment by ZaberZiv** [comment]
Thanks for explanation.
Well yes, I just want to delete all existing pre-releases before add new one.
Just tried run your script and it didn't help.

**Comment by thadguidry** [comment]
What was the error or log output?

**Comment by ZaberZiv** [comment]
Run dev-drprasad/delete-older-releases@v0.3.3
💬  no `repo` name given. fall-ing back to this repo
🌶  given `keep_latest` is 0, this will wipe out all releases
🔖  corresponding tags also will be deleted
🔖  Remove only prerelease
🌶  given `keep_min_download_counts` is 0, this will not enable the download count removal rule
🌶  given `delete_expired_data` is  0
🌶  failed to get list of releases <- Not Found
exiting...

**Comment by thadguidry** [comment]
I think we might have exposed a recently introduced bug in their GitHub Releases API... I've detailed what might be happening in another user's similar report in issue #44 , so please take a look at that issue.  We'll keep this issue open until GitHub helps resolve things or explains more what changed.
