### ISSUE TITLE
Prerelease vs Release

### ISSUE THREAD

**Issue by aquacash5** [dev-drprasad/delete-older-releases#7]
It would be awesome if we could specify that the action should only be taken on releases marked `prerelease`.

**Comment by dennistruemper** [comment]
Hi @aquacash5  if your prereleases contain a pettern (like v1.1.1test.1) take a look at https://github.com/dev-drprasad/delete-older-releases/pull/8 
I created this to delete only old prereleases containing the word test.

**Comment by thadguidry** [comment]
This should have 2 optionals:
1. Whether to delete a matching prerelease. #default = false
2. Whether to delete the tag of a matching prerelease. #default = true

I see other Marketplace Actions that have an additional 3rd option to keep the last X number of prereleases where the latest prerelease is reserved and never deleted unless a `-1` is passed as input to signify "delete ALL prereleases".
